# -*- coding: utf-8 -*-
"""sketch-based-network-traffic-monitoring

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AgtAFVpAp7pDBCmZFLA_tbunbwnFqenL

Modern networks generate massive volumes of traffic every second. Monitoring traffic in real time is critical for:

- Network security monitoring
- DDoS detection
- Network performance analysis
- Traffic engineering

However, storing all packets is expensive. Modern systems use **compact probabilistic data structures called sketches** to estimate flow statistics efficiently.

## Objective

This prototype demonstrates how sketch-based algorithms can monitor network traffic streams and detect abnormal traffic bursts.

Pipeline:

Traffic Stream → Flow Extraction → Count-Min Sketch → Heavy Hitter Detection → Anomaly Detection → Visualization
"""

!pip install numpy pandas matplotlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import hashlib
from collections import defaultdict

"""Simulate Network Traffic"""

def generate_ip():
    return ".".join(str(random.randint(0,255)) for _ in range(4))

traffic = []

for i in range(2000):

    # simulate normal traffic
    src = generate_ip()
    dst = generate_ip()

    # inject burst attack traffic
    if random.random() < 0.05:
        src = "192.168.1.1"
        dst = "10.0.0.1"

    packet = {
        "source": src,
        "destination": dst,
        "size": random.randint(40,1500),
        "timestamp": i
    }

    traffic.append(packet)

df = pd.DataFrame(traffic)

df.head()



"""Count-Min Sketch Implementation"""

class CountMinSketch:

    def __init__(self, width, depth):
        self.width = width
        self.depth = depth
        self.table = np.zeros((depth, width))

    def hash(self, item, seed):
        return int(hashlib.md5((item + str(seed)).encode()).hexdigest(),16) % self.width

    def add(self, item):
        for i in range(self.depth):
            index = self.hash(item, i)
            self.table[i][index] += 1

    def estimate(self, item):
        estimates = []

        for i in range(self.depth):
            index = self.hash(item, i)
            estimates.append(self.table[i][index])

        return min(estimates)

cms = CountMinSketch(width=200, depth=5)

"""Process Traffic Stream"""

flow_counts = []

for _, row in df.iterrows():

    flow = row["source"] + "-" + row["destination"]

    cms.add(flow)

    estimate = cms.estimate(flow)

    flow_counts.append(estimate)

"""Heavy Hitter Detection"""

threshold = 20

heavy_hitters = []

for i,count in enumerate(flow_counts):

    if count > threshold:
        heavy_hitters.append(i)

print("Detected heavy hitter packets:", heavy_hitters[:20])

plt.figure(figsize=(12,5))

plt.plot(flow_counts)

plt.title("Estimated Network Flow Frequency Over Time")

plt.xlabel("Packet Index")

plt.ylabel("Estimated Flow Count")

plt.show()

"""Burst Detection"""

window = 50
burst_points = []

for i in range(len(flow_counts)-window):

    avg = np.mean(flow_counts[i:i+window])

    if avg > 10:
        burst_points.append(i)

print("Detected burst windows:", burst_points[:10])

"""Visualize Anomalies"""

plt.figure(figsize=(12,5))

plt.plot(flow_counts, label="Flow Frequency")

for p in burst_points[:10]:
    plt.axvline(p, color='red', alpha=0.3)

plt.legend()

plt.title("Traffic Burst Detection")

plt.show()

"""## Conclusion

This prototype demonstrates how compact sketch data structures can monitor streaming network traffic efficiently.

Key observations:

- Sketch-based methods allow fast frequency estimation
- Traffic bursts can indicate abnormal behavior
- Such techniques are widely used in modern network monitoring systems

Future work may include applying these techniques to real network traffic datasets and integrating machine learning for advanced anomaly detection.
"""

